// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMailSubscribe = "mail_subscribe"

// MailSubscribe mapped from table <mail_subscribe>
type MailSubscribe struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email    string    `gorm:"column:email" json:"email"`
	CreateAt time.Time `gorm:"column:create_at" json:"create_at"`
}

// TableName MailSubscribe's table name
func (*MailSubscribe) TableName() string {
	return TableNameMailSubscribe
}
