// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProcessedBlock = "processed_block"

// ProcessedBlock mapped from table <processed_block>
type ProcessedBlock struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BlockNumber int64     `gorm:"column:block_number;not null" json:"block_number"`
	CreateAt    time.Time `gorm:"column:create_at" json:"create_at"`
	Status      int32     `gorm:"column:status" json:"status"`
}

// TableName ProcessedBlock's table name
func (*ProcessedBlock) TableName() string {
	return TableNameProcessedBlock
}
