// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePropertyRental = "property_rental"

// PropertyRental mapped from table <property_rental>
type PropertyRental struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PropertInfoID int64     `gorm:"column:propert_info_id" json:"propert_info_id"`
	SlotID        int64     `gorm:"column:slot_id" json:"slot_id"`
	TotalAmount   float64   `gorm:"column:total_amount" json:"total_amount"`
	StartTime     int64     `gorm:"column:start_time" json:"start_time"`
	EndTime       int64     `gorm:"column:end_time" json:"end_time"`
	TxHash        string    `gorm:"column:tx_hash" json:"tx_hash"`
	CreateAt      time.Time `gorm:"column:create_at" json:"create_at"`
}

// TableName PropertyRental's table name
func (*PropertyRental) TableName() string {
	return TableNamePropertyRental
}
