// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePropertyInfo = "property_info"

// PropertyInfo 房屋信息，包括初始代币发售（ITO），租金，总回报，备注（Property Information including Initial Token Offering (ITO), Rents, Total Returns, Remarks）
type PropertyInfo struct {
	ID                     int64     `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                                                            // 主键ID
	PropertyNumber         string    `gorm:"column:property_number;comment:房产编号（Property number）" json:"property_number"`                            // 房产编号（Property number）
	Address1               string    `gorm:"column:address1;comment:地址1（Address 1）" json:"address1"`                                                 // 地址1（Address 1）
	Address2               string    `gorm:"column:address2;comment:地址2（Address 2）" json:"address2"`                                                 // 地址2（Address 2）
	City                   string    `gorm:"column:city;comment:城市（City）" json:"city"`                                                               // 城市（City）
	County                 string    `gorm:"column:county;comment:县（County）" json:"county"`                                                          // 县（County）
	Country                string    `gorm:"column:country;comment:国家（Country）" json:"country"`                                                      // 国家（Country）
	Postcode               string    `gorm:"column:postcode;comment:邮政编码（Postcode）" json:"postcode"`                                                 // 邮政编码（Postcode）
	PropertyType           string    `gorm:"column:property_type;comment:房产类型（Property type）" json:"property_type"`                                  // 房产类型（Property type）
	Bedrooms               int32     `gorm:"column:bedrooms;comment:卧室数量（Bedrooms）" json:"bedrooms"`                                                 // 卧室数量（Bedrooms）
	Bathrooms              int32     `gorm:"column:bathrooms;comment:浴室数量（Bathrooms）" json:"bathrooms"`                                              // 浴室数量（Bathrooms）
	InternalSize           int32     `gorm:"column:internal_size;comment:内部面积（平方英尺，Internal Size）" json:"internal_size"`                             // 内部面积（平方英尺，Internal Size）
	Tenure                 string    `gorm:"column:tenure;comment:租赁类型（Tenure）" json:"tenure"`                                                       // 租赁类型（Tenure）
	PropertyDescription    string    `gorm:"column:property_description;comment:房产描述（Property description）" json:"property_description"`             // 房产描述（Property description）
	PropertyManagement     string    `gorm:"column:property_management;comment:物业管理（Property management）" json:"property_management"`                // 物业管理（Property management）
	PropertyInsurance      string    `gorm:"column:property_insurance;comment:房产保险（Property insurance）" json:"property_insurance"`                   // 房产保险（Property insurance）
	Tenancy                string    `gorm:"column:tenancy;comment:租约信息（Tenancy）" json:"tenancy"`                                                    // 租约信息（Tenancy）
	Neighbourhood          string    `gorm:"column:neighbourhood;comment:社区信息（Neighbourhood）" json:"neighbourhood"`                                  // 社区信息（Neighbourhood）
	TotalInvestmentValue   float64   `gorm:"column:total_investment_value;comment:总投资价值（Total Investment Value，美元）" json:"total_investment_value"`   // 总投资价值（Total Investment Value，美元）
	UnderlyingAssetPrice   float64   `gorm:"column:underlying_asset_price;comment:基础资产价格（Underlying Asset Price，美元）" json:"underlying_asset_price"`  // 基础资产价格（Underlying Asset Price，美元）
	ClosingCosts           float64   `gorm:"column:closing_costs;comment:成交费用（Closing Costs，美元）" json:"closing_costs"`                               // 成交费用（Closing Costs，美元）
	UpfrontSpvFees         float64   `gorm:"column:upfront_spv_fees;comment:前期SPV费用（Upfront SPV Fees，美元）" json:"upfront_spv_fees"`                   // 前期SPV费用（Upfront SPV Fees，美元）
	OperatingReserve       float64   `gorm:"column:operating_reserve;comment:运营储备金（Operating Reserve，美元）" json:"operating_reserve"`                  // 运营储备金（Operating Reserve，美元）
	AnnualGrossRents       float64   `gorm:"column:annual_gross_rents;comment:年度总租金收益（Annual Gross Rents，美元）" json:"annual_gross_rents"`             // 年度总租金收益（Annual Gross Rents，美元）
	CouncilTax             float64   `gorm:"column:council_tax;comment:市政税（Council Tax，美元）" json:"council_tax"`                                      // 市政税（Council Tax，美元）
	HomeownersInsurance    float64   `gorm:"column:homeowners_insurance;comment:房主保险费（Homeowners Insurance，美元）" json:"homeowners_insurance"`         // 房主保险费（Homeowners Insurance，美元）
	PropertyManagementFees float64   `gorm:"column:property_management_fees;comment:物业管理费（Property Management，美元）" json:"property_management_fees"`  // 物业管理费（Property Management，美元）
	Utilities              float64   `gorm:"column:utilities;comment:水电费（Utilities，美元）" json:"utilities"`                                            // 水电费（Utilities，美元）
	LegalFees              float64   `gorm:"column:legal_fees;comment:法律费用（Legal Fees，美元）" json:"legal_fees"`                                        // 法律费用（Legal Fees，美元）
	AnnualCashflow         float64   `gorm:"column:annual_cashflow;comment:年度现金流量（Annual Cashflow，美元）" json:"annual_cashflow"`                       // 年度现金流量（Annual Cashflow，美元）
	ProjectedAnnualReturn  float64   `gorm:"column:projected_annual_return;comment:预计年度回报率（Projected Annual Return）" json:"projected_annual_return"` // 预计年度回报率（Projected Annual Return）
	ProjectedRentalYield   float64   `gorm:"column:projected_rental_yield;comment:预计租金收益率（Projected Rental Yield）" json:"projected_rental_yield"`    // 预计租金收益率（Projected Rental Yield）
	ProjectedAppreciation  float64   `gorm:"column:projected_appreciation;comment:预计升值率（Projected Appreciation）" json:"projected_appreciation"`      // 预计升值率（Projected Appreciation）
	HistoricalRentalYield  float64   `gorm:"column:historical_rental_yield;comment:历史租金收益率（Historical Rental Yield）" json:"historical_rental_yield"` // 历史租金收益率（Historical Rental Yield）
	CreateAt               time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间（Create Time）" json:"create_at"`         // 创建时间（Create Time）
	PropertyStatus         int32     `gorm:"column:property_status;comment:房屋状态（Property Status）" json:"property_status"`                            // 房屋状态（Property Status）
	LeaseStatus            int32     `gorm:"column:lease_status;comment:租赁状态" json:"lease_status"`                                                   // 租赁状态
	Creator                int64     `gorm:"column:creator;comment:创建人（Creator）" json:"creator"`                                                     // 创建人（Creator）
	Longitude              string    `gorm:"column:longitude;comment:经度" json:"longitude"`                                                           // 经度
	Latitude               string    `gorm:"column:latitude;comment:维度" json:"latitude"`                                                             // 维度
}

// TableName PropertyInfo's table name
func (*PropertyInfo) TableName() string {
	return TableNamePropertyInfo
}
