// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePropertyTransaction = "property_transaction"

// PropertyTransaction mapped from table <property_transaction>
type PropertyTransaction struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TxHash        string    `gorm:"column:tx_hash" json:"tx_hash"`
	FromAddr      string    `gorm:"column:from_addr" json:"from_addr"`
	ToAddr        string    `gorm:"column:to_addr" json:"to_addr"`
	SoltID        int64     `gorm:"column:solt_id" json:"solt_id"`
	PropertInfoID string    `gorm:"column:propert_info_id" json:"propert_info_id"`
	TxTime        time.Time `gorm:"column:tx_time" json:"tx_time"`
	Amount        string    `gorm:"column:amount" json:"amount"`
	Spent         int32     `gorm:"column:spent;comment:是否被花费，默认是否" json:"spent"` // 是否被花费，默认是否
	CreateAt      time.Time `gorm:"column:create_at" json:"create_at"`
}

// TableName PropertyTransaction's table name
func (*PropertyTransaction) TableName() string {
	return TableNamePropertyTransaction
}
